### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by EmFlo14** [G0lG013/Unescapable#5]
Hey, great game by the way, I love the shooting mechanics and it was really fun to play

One issue I noticed in the game is that when you finish a level, it gets pretty confusing to know where to go next. I never knew which wall I had to go through in order to get to the next level so it took me a while to figure it out by trying multiple walls to see which one worked.

Also, I noticed that when I place my curser over the character it'll glitch. This probably normal since the cursor is telling the character where to go, but as a suggestion I think it would be a good idea if you guys implemented a feature where if the mouse is hovering over the character or at a certain close distance to it, the character will stop moving instead of glitching.

Other than that I thought it was really good and you guys did a really great job!

- Emma Florent

**Comment by RachelleBadua** [comment]
We have completed the issue about where to go and what entrance to go through to enter another stage by putting walls on each maps so you can find your way through the stages. We didn't get to complete the issue about the curser because we did not have enough time to do it and we were working on other components of the game.
